### ISSUE TITLE
snprintf usage bug?

### ISSUE THREAD

**Issue by davidgfnet** [matrixssl/matrixssl#20]
I see that in matrixssl.c:3600 the following call is used:

         snprintf(ip, 15, "%u.%u.%u.%u",

According to the spec the "n" is the number of bytes, which means the output can be up to n-1 characters. Since ip is a 16 byte array, the correct "n" would be 16, and no `ip[15] = '\0';` is needed.

**Comment by CarloWood** [comment]
Hi david. I noted that nobody seems to be maintaining matrixssl anymore(?)... 25 issues are still open on github. You are correct that sizeof(ip) (or 16) would be the more correct value, but using 15 doesn't harm in this case because below this snprintf the trailing zero is added anyway. I patched this nevertheless in my repository (https://github.com/CarloWood/matrixssl/commit/fbba78ec5b3df4db031a71e973a8f7957a0479fd)

**Comment by mkontio** [comment]
Hi Carlo!
MatrixSSL commercial edition (Verimatrix TLS Toolkit) is maintained by Verimatrix (previously known as Inside Secure). When we release a new commercial version we also update the gihub master branch accordingly. I agree that the pull requests and open issues deserve more attention and bandwidth, I will prioritise that with the development team.
