### ISSUE TITLE
"Yarrow PRNG" ERROR!

### ISSUE THREAD

**Issue by liuning587** [matrixssl/matrixssl#8]
Hello, I can't compile the file "yarrow.c", when I define **USE_YARROW**
here is code (yarrow.c,line:92~95):
```
92	/* store result */
93	if ((err = psSha256Final(&md, prng->pool)) != SHA256_HASH_SIZE) {
94		return err;
95	}
```
But in cryptoApi.h, psSha256Final return type is **void**
```
PSPUBLIC void psSha256Final(psSha256_t *sha256,
				unsigned char hash[SHA256_HASHLEN]);
```

**Comment by matrixssl-admin** [comment]
Hello, Liu Ning.


Yarrow is actually deprecated functionality (better to use psGetEntropy and e.g. /dev/urandom directly). SHA-256, SHA-1 and AES API have been changed since this code was previously used. We're having a new SW version getting finished very soon now and it fixes the compilation issue.


In meanwhile, if you need to locally patch the code, then you can use:


     psSha256Final(&md, prng->pool);

instead of

     if ((err = psSha256Final(&md, prng->pool)) != SHA256_HASH_SIZE) {
         return err;
     }


And

     if ((err = psAesInitBlockKey(&ctx->key, ctx->pool, keylen,
                                  PS_AES_ENCRYPT)) != PS_SUCCESS) {

instead of

     if ((err = psAesInitBlockKey(ctx->pool, keylen, &ctx->key)) != PS_SUCCESS) {

And

    psAesEncryptBlock(&ctx->key, ctx->ctr, ctx->pad);

instead of

    psAesEncryptBlock(ctx->ctr, ctx->pad, &ctx->key);



Hope this helps,


Marko Nippula

INSIDE Secure

SENIOR SOFTWARE ARCHITECT
EMBEDDED SOFTWARE

CONFIDENTIALITY - This e-mail and any attachments hereto are intended only for use by the addressee(s) named herein and may contain confidential information. If you are not the named recipient, please notify the sender immediately and do not disclose the contents to any person, use it for any purpose, or store or copy the information on any medium. Please permanently delete the original copy of this e-mail and/or any attachments thereto and any printout thereof. Thank you.



________________________________
Lähettäjä: liu ning <notifications@github.com>
Lähetetty: 10. marraskuuta 2016 13:00
Vastaanottaja: matrixssl/matrixssl
Aihe: [matrixssl/matrixssl] "Yarrow PRNG" ERROR! (#8)


Hello, I can't compile the file "yarrow.c", when I define USE_YARROW
here is code (yarrow.c,line:92~95):

92      /* store result */
93      if ((err = psSha256Final(&md, prng->pool)) != SHA256_HASH_SIZE) {
94              return err;
95      }


But in cryptoApi.h, psSha256Final return type is void

PSPUBLIC void psSha256Final(psSha256_t *sha256,
                                unsigned char hash[SHA256_HASHLEN]);


-

**Comment by liuning587** [comment]
Thank you.
